[package]
name = "bromberg_sl2"
version = "0.1.0"
authors = ["Ben Weinstein-Raun <root@benwr.net>"]
edition = "2018"
license = "CC0"
repository = "https://github.com/benwr/bromberg_sl2"
categories = ["cryptography", "algorithms"]
keywords = ["hashing", "sl2", "homomorphic", "monoidal", "tillich-zemor"]

[dependencies]

[dev-dependencies]
quickcheck = "0.9"
num-bigint = "0.3"
